name: Atualizar Federal

on:
  workflow_dispatch:

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Executar motor
        run: node scripts/atualizar-federal.js